#Possible actions
string GET=get
string GET_TEMPLATE=get_template
string RESOLVE=resolve
string GET_RECURSIVE=get_recursive

string action
string context
WmElement element
string relation_filter
string type_filter
---
string snapshot_id
WmElement[] elements
