#!/usr/bin/env python

import skiros2_task.core.pddl_interface as pddl
#import rospy
import rospkg

if __name__ == '__main__':
    #rospy.init_node("test_pddl", anonymous=False)
    pddl_interface = pddl.PddlInterface(rospkg.RosPack().get_path("skiros2_task"))
    print pddl_interface.invokePlanner(False)
