#!/usr/bin/env python

import sys
import skiros2_world_model.ros.world_model_interface as wmi
import skiros2_common.tools.logger as log


def printUsage():
    print("""usage: scene [<command>] [<arg1>].
Possible commands: load, save, add.
Examples:
edit_scene load file.owl
edit_scene add large_box_test_starter""")


if __name__ == '__main__':
    print(sys.argv)
    if len(sys.argv) == 1:
        printUsage()
    else:
        wmi = wmi.WorldModelInterface()
        if sys.argv[1] == "save":
            wmi.save(sys.argv[2])
        elif sys.argv[1] == "load":
            wmi.load(sys.argv[2])
        elif sys.argv[1] == "add":
            print("ID: {}".format(wmi.instanciate(sys.argv[2])._id))
        else:
            log.error("InputError", "Command {} not recognized".format(sys.argv[1]))
            printUsage()
