#!/usr/bin/env python

import skiros2_world_model.ros.world_model_interface as wmi
import sys


def _print_recursive(wmi, name, d, indentation=""):
    e = d[name]
    print("{}->{}".format(indentation, e.printState()))
    for r in e.getRelations(subj="-1", pred=wmi.get_sub_properties("skiros:spatiallyRelated")):
        _print_recursive(wmi, r['dst'], d, indentation + "--")


def print_scene(wmi):
    (scene, scene_id) = wmi.get_scene()
    utility_dict = dict()
    for e in scene:
        utility_dict[e.id] = e
    _print_recursive(wmi, "skiros:Scene-0", utility_dict)


if __name__ == '__main__':
    print("usage: view_scene [<predicate>]. Default: skiros:spatiallyRelated. Other common predicates: skiros:sceneProperty, skiros:skillProperty.")
    predicate = "skiros:spatiallyRelated"
    if len(sys.argv) > 1:
        predicate = sys.argv[1]
    wmi = wmi.WorldModelInterface()
    print_scene(wmi)
